version: '3.9'

services:
  postgres_dev:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
  postgres_test:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}

volumes:
  postgres:
