version: '3.9'

services:
  postgres:
    image: postgres
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
